### ISSUE TITLE
Error while verifying the Quote and geting the Coordinator’s Root-Certificate

### ISSUE THREAD

**Issue by mahiuddinalkamal** [edgelesssys/emojivoto#12]
Hello,

I am trying to deploy the emojivoto demo in AKS using Marblerun. 

However, I am currently stuck at step 3.4 "Verify the Quote and get the Coordinator’s Root-Certificate".

I am attaching the error log with additional logs here. 

[Marblerun error.txt](https://github.com/edgelesssys/emojivoto/files/6084291/Marblerun.error.txt)

**Comment by m1ghtym0** [comment]
The problem seems to be that you're not configuring the remote access for the Marblerun Client API when deploying on AKS.
While using Minikube you can just use the `kubectl port-forward` command, in AKS you need to make the `coordinator-client-api ` service accessible from the outside world.
When running on AKS a LoadBalancer will be assigned automatically the service and you'll receive a public IP address.
In the `tools/aks_install.sh` we assign a DNS name to the public IP of the LoadBalancer:

```
# set dns for coordinator
echo "[*] Setting DNS for the marblerun-coordinator"
IP=""
echo -n "[*] Waiting for LoadBalancer to assign a public IP..."
until [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]];
do
    IP=$(kubectl -n marblerun get svc coordinator-client-api -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
    echo -n "."
    sleep 3
done
PUBLICIPID=$(az network public-ip list --query "[?ipAddress!=null]|[?contains(ipAddress, '$IP')].[id]" --output tsv)
az network public-ip update --ids $PUBLICIPID --dns-name "$MARBLERUN_DNSNAME" > /dev/null
MARBLERUN=""
until [[ $MARBLERUN == "$MARBLERUN_DNSNAME."* ]]
do
    MARBLERUN="$(az network public-ip show --ids $PUBLICIPID --query "[dnsSettings.fqdn]" --output tsv):25555"
    echo -n "."
    sleep 3
done
echo ""
echo -e "[$okStatus] Done"
``` 

You have two options here:
1. Either you follow this approach and set the DNS correctly for the LoadBalancer IP
2. Or you connect to the public IP directly. Note that in this case you'll need to disable the certificate verification (It might take a few seconds until the IP is assigned to the service)
 ```
$ kubectl -n marblerun get svc
NAME                     TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)           AGE
coordinator-client-api   LoadBalancer   10.0.12.122   51.132.168.253   25555:30915/TCP   4m7s
coordinator-mesh-api     ClusterIP      10.0.24.45    <none>           25554/TCP         4m7s
$ era -c coordinator-era.json -h 51.132.168.253:25555 -o marblerun.crt
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
SUCCESS, certificate writen to marblerun.crt
 ```

**Comment by mahiuddinalkamal** [comment]
I set up the DNS name to the public IP of the LoadBalancer and tried again. Now facing a different error. 

`$ era -c coordinator-era.json -h $MARBLERUN -o marblerun.crt`
panic: Get "https://marblerun.westeurope.cloudapp.azure.com/quote": dial tcp 20.71.83.83:443: connect: connection timed out

goroutine 1 [running]:
main.main()
	/home/moritz/edgeless/era/cmd/era/main.go:32 +0x433

As far as I know, Microsoft does not provide "SGX Quote Helper" feature now for remote attestation to a newly created AKS with ConfCom Addon, so is it trying to access it? Is that the reason behind this error?

**Comment by m1ghtym0** [comment]
Are you sure you're using the right port? Default port of the `coordinator-client-api` is 25555.

**Comment by mahiuddinalkamal** [comment]
Yeah, I forgot about the port. It's working now. However, I am now facing another error at step 4:

`curl --cacert marblerun.crt --data-binary @tools/manifest.json "https://$MARBLERUN/manifest"`

curl: (60) SSL: no alternative certificate subject name matches target host name 'marblerun.westeurope.cloudapp.azure.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by m1ghtym0** [comment]
> curl: (60) SSL: no alternative certificate subject name matches target host name 'marblerun.westeurope.cloudapp.azure.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

The problem is when your installing Marblerun via the helm chart, e.g.:
```
helm install marblerun-coordinator edgeless/marblerun-coordinator \
    --create-namespace \
    -n marblerun \
    --set coordinator.hostname=YOUR_DOMAIN
```

You have to specify `YOUR_DOMAIN`. The coordinator will issue a self-signed certificate and obtain a quote for it.
This certificate will be used for TLS on the client API.
When you're configuring the DNS for `coordinator-client-api` LoadBalancer service, you need to make sure you're using the same `YOUR_DOMAIN`.
That is what curl is complaining about. `$MARBLERUN` points to `marblerun.westeurope.cloudapp.azure.com`, but the client API certificate was issued for a different domain.

**Comment by mahiuddinalkamal** [comment]
Thanks. I understood the problem and now it's resolved :)
